In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Amit", "Riya", "Sam", "Neha", "Raj"],              # stored as key value pairs 
    "Age": [21, 22, 20, 23, 21],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Nagpur"],
    "Marks": [85, 90, 78, 92, 88]
}

In [4]:
df = pd.DataFrame(data)             # creating a data frame 
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [5]:
# The index 0 to 4 is created automatically.

In [6]:
rows = [["Amit", 21], ["Riya", 22], ["Sam", 20], ["Neha" ,23]]       # creating a new 2D array (rows)

In [7]:
df_list = pd.DataFrame(rows, columns=["Name", "Age"])      # name and age cols are created from rows 
print(df_list)

   Name  Age
0  Amit   21
1  Riya   22
2   Sam   20
3  Neha   23

In [8]:
records = [                                           # Creating a new dictionary
    {"Name": "Amit", "Age": 21},                      # 2 cols    (1 missing)
    {"Name": "Riya", "Age": 22, "City": "Mumbai"}     # 3 cols    (all 3 cols)
]
df_rec = pd.DataFrame(records)                        # converting records dict to dataframe
print(df_rec)                                         # NaN = Not a Number (meaning missing)

   Name  Age    City
0  Amit   21     NaN
1  Riya   22  Mumbai

In [9]:
# np.arange(1, 10) creates numbers 1 to 9.

In [10]:
arr = np.arange(1, 10).reshape(3, 3)            # creating 1 to 9 nums and then shaping them into 3*3
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [11]:
# .reshape(3, 3) makes them a 3x3 grid.
# columns= and index= label the columns and rows.

In [12]:
df_np = pd.DataFrame(arr, columns=["A", "B", "C"], index=["r1", "r2", "r3"])     # name the cols and then index(rows)
print(df_np)

    A  B  C
r1  1  2  3
r2  4  5  6
r3  7  8  9

In [13]:
s1 = pd.Series([85, 90, 78], index=["Amit", "Riya", "Sam"])     # creating new series with indices 
s2 = pd.Series([21, 22, 20], index=["Amit", "Riya", "Sam"])     # creating new series with same indices 
df_s = pd.DataFrame({"Marks": s1, "Age": s2})                   # Creating dataframe using s1 and s2 and naming cols as marks and age
print(df_s)

      Marks  Age
Amit     85   21
Riya     90   22
Sam      78   20

In [14]:
# shape gives (rows, columns). Here 5 rows and 4 columns.
# size gives the total number of cells (5 x 4 = 20).
# ndim is always 2 for a DataFrame.
# columns gives the column names as an Index object.
# index gives the row labels. RangeIndex(start=0, stop=5, step=1) is the automatic 0 to 4 index.
# dtypes gives the data type of each column. Text columns show as object.

In [15]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [16]:
print(df.shape)          # shape -> rows * cols

(5, 4)

In [17]:
print(df.size)           # size -> rows * cols

20

In [18]:
print(df.ndim)           # dimension of df

2

In [19]:
print(df.columns)        # print cols of df

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

In [20]:
print(df.index)          # indexing info (starting index , stoping index , steps)

RangeIndex(start=0, stop=5, step=1)

In [21]:
print(df.dtypes)         # data types of each col

Name       str
Age      int64
City       str
Marks    int64
dtype: object

In [22]:
# values gives the whole table as a NumPy array.
# columns.tolist() converts the column names to a normal Python list.
# len(df) gives the number of rows.
# empty is True only if the DataFrame has no data.

In [23]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [24]:
print(df.values)                    # gives values accourding to dtypes in 2D array

[['Amit' 21 'Pune' 85]
 ['Riya' 22 'Mumbai' 90]
 ['Sam' 20 'Delhi' 78]
 ['Neha' 23 'Pune' 92]
 ['Raj' 21 'Nagpur' 88]]

In [25]:
print(df.columns.tolist())          # columns to list (array)

['Name', 'Age', 'City', 'Marks']

In [26]:
print(len(df))                      # printing len of df (number of rows)

5

In [27]:
print(df.empty)                     # id df empty

False

In [28]:
# head(n) shows the first n rows (default 5).
# tail(n) shows the last n rows (default 5).
# sample(n) picks n random rows, which is good for a quick look at big data.

In [29]:
print(df.head(2))                   # starting 2 rows

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90

In [30]:
print(df.tail(2))                   # ending 2 rows

   Name  Age    City  Marks
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [31]:
print(df.sample(2))                # it is random and changes every run.

   Name  Age    City  Marks
4   Raj   21  Nagpur     88
1  Riya   22  Mumbai     90

In [32]:
# info() prints a structural summary, so don’t wrap it in print(). 
# It shows the number of rows, each column’s name, how many values are not missing, 
# each column’s dtype, and the memory used. 
# If a column had missing values, its Non-Null Count would be less than 5. 
# The memory number varies by version.

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [34]:
# describe() gives statistics for numeric columns only by default. 
# The text columns Name and City are skipped. To include them, use df.describe(include="all").

In [35]:
print(df.describe())

             Age      Marks
count   5.000000   5.000000
mean   21.400000  86.600000
std     1.140175   5.458938
min    20.000000  78.000000
25%    21.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  90.000000
max    23.000000  92.000000

In [36]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [37]:
df.describe(include="all")

        Name        Age  City      Marks
count      5   5.000000     5   5.000000
unique     5        NaN     4        NaN
top     Amit        NaN  Pune        NaN
freq       1        NaN     2        NaN
mean     NaN  21.400000   NaN  86.600000
std      NaN   1.140175   NaN   5.458938
min      NaN  20.000000   NaN  78.000000
25%      NaN  21.000000   NaN  85.000000
50%      NaN  21.000000   NaN  88.000000
75%      NaN  22.000000   NaN  90.000000
max      NaN  23.000000   NaN  92.000000

In [38]:
print(df["Name"])            # prints name col with index

0    Amit
1    Riya
2     Sam
3    Neha
4     Raj
Name: Name, dtype: str

In [39]:
print(type(df["Name"]))        # gives data type of df having 2 cols

<class 'pandas.Series'>

In [40]:
# The double brackets matter. 
# The outer [] is the selection and the inner [] is a Python list of column names. 
# One bracket gives a Series, and a list inside brackets gives a DataFrame.

In [41]:
print(df[["Name", "Marks"]])    # gives 2 cols in df

   Name  Marks
0  Amit     85
1  Riya     90
2   Sam     78
3  Neha     92
4   Raj     88

In [42]:
print(type(df[["Name", "Marks"]]))   # gives data type of df having 2 cols

<class 'pandas.DataFrame'>

In [43]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [44]:
print(df.Marks)           # printing marks of df side by side

0    85
1    90
2    78
3    92
4    88
Name: Marks, dtype: int64

In [45]:
print(df.Marks.mean())     # prints min of marks

86.6

In [46]:
# iloc[0] returns the first row as a Series. Its index is the column names and its name is the row label 0.

In [47]:
print(df.iloc[0])          # prints 1st row

Name     Amit
Age        21
City     Pune
Marks      85
Name: 0, dtype: object

In [48]:
# iloc[1:3] gives rows at positions 1 and 2 (end excluded).
# iloc[0, 1] gives the cell at row position 0 and column position 1, which is Amit’s age.

In [49]:
print(df.iloc[1:3])         # prints rows from 2nd to 3rd

   Name  Age    City  Marks
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78

In [50]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [51]:
print(df.iloc[0, 0])

Amit

In [52]:
print(df.iloc[0, 1])

21

In [53]:
print(df.iloc[0, 2])

Pune

In [54]:
print(df.iloc[0, 3])

85

In [55]:
print(df.iloc[3, 2])

Pune

In [56]:
print(df.iloc[4, 3])

88

In [57]:
df_idx = df.set_index("Name")                            # Make column as index to dataframe 
print(df_idx)

      Age    City  Marks
Name
Amit   21    Pune     85
Riya   22  Mumbai     90
Sam    20   Delhi     78
Neha   23    Pune     92
Raj    21  Nagpur     88

In [58]:
# set_index("Name") turns the Name column into the row labels. It returns a new DataFrame and leaves df unchanged.

In [59]:
print(df_idx.loc["Riya"])                  # Access a row by label with loc

Age          22
City     Mumbai
Marks        90
Name: Riya, dtype: object

In [60]:
# loc selects by label, while iloc selects by position.

In [61]:
df_back = df_idx.reset_index()            # reset index
print(df_back.head())                     # this is all dataframe (All 5 rows)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [62]:
# reset_index() moves the index back into a regular column and restores 0, 1, 2... labels.

## Basic column operations on a DataFrame

In [63]:
print(df["Marks"] + 5)       # A column is a Series, so vectorized math works exactly as before.

0    90
1    95
2    83
3    97
4    93
Name: Marks, dtype: int64

In [64]:
# df.columns is a pandas Index containing the column names. 
# .tolist() converts it into a regular Python list.

In [65]:
df["Percentage"] = df["Marks"] / 100 * 100       # Add a new column
print(df.head())

   Name  Age    City  Marks  Percentage
0  Amit   21    Pune     85        85.0
1  Riya   22  Mumbai     90        90.0
2   Sam   20   Delhi     78        78.0
3  Neha   23    Pune     92        92.0
4   Raj   21  Nagpur     88        88.0

In [66]:
df["Passed"] = df["Marks"] > 80                      # Add a True/False column
print(df[["Name", "Marks", "Passed"]])

   Name  Marks  Passed
0  Amit     85    True
1  Riya     90    True
2   Sam     78   False
3  Neha     92    True
4   Raj     88    True

In [67]:
df = df.drop(columns=["Percentage", "Passed"])        # Delete a columns named percentage and 
print(df.columns.tolist())                            # new list of cols

['Name', 'Age', 'City', 'Marks']

In [68]:
# df["Marks"].mean() works on one column and gives a single number.
# df.mean(numeric_only=True) works on all numeric columns and gives one result per column. 
# numeric_only=True skips the text columns, otherwise pandas may raise an error.

In [69]:
print(df["Marks"].mean())

86.6

In [70]:
print(df["Age"].max())

23

In [71]:
print(df.mean(numeric_only=True))        # for cols having numeric values give their mean

Age      21.4
Marks    86.6
dtype: float64

In [72]:
print(df)

   Name  Age    City  Marks
0  Amit   21    Pune     85
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [73]:
print(df.T)                             # T swaps rows and columns, exactly like NumPy’s .T   (T -> Transpose)

          0       1      2     3       4
Name   Amit    Riya    Sam  Neha     Raj
Age      21      22     20    23      21
City   Pune  Mumbai  Delhi  Pune  Nagpur
Marks    85      90     78    92      88

In [74]:
# copy() creates an independent DataFrame, so changing df_copy does not change df. loc[0, "Marks"] means row label 0, column “Marks”.

In [75]:
df_copy = df.copy()

In [76]:
df_copy.loc[0, "Marks"] = 0

In [77]:
print(df.loc[0, "Marks"])

85

In [78]:
print(df_copy)

   Name  Age    City  Marks
0  Amit   21    Pune      0
1  Riya   22  Mumbai     90
2   Sam   20   Delhi     78
3  Neha   23    Pune     92
4   Raj   21  Nagpur     88

In [91]:
df_copy.loc[:, "Marks"] = 0

In [93]:
df_copy

   Name  Age    City  Marks
0  Amit   21    Pune      0
1  Riya   22  Mumbai      0
2   Sam   20   Delhi      0
3  Neha   23    Pune      0
4   Raj   21  Nagpur      0